<a href="https://colab.research.google.com/github/msali64/Array/blob/main/Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [7]:
k=[4,2.45765,9,89.999,40,'hyderabad']
k

[4, 2.45765, 9, 89.999, 40, 'hyderabad']

In [8]:
pd.Series(k)

0            4
1      2.45765
2            9
3       89.999
4           40
5    hyderabad
dtype: object

In [14]:
a=np.random.randint(20,50,15)
a

array([34, 41, 29, 47, 39, 31, 25, 29, 34, 23, 23, 45, 21, 37, 30])

In [15]:
a.ndim

1

In [18]:
pd.Series(a)

0     34
1     41
2     29
3     47
4     39
5     31
6     25
7     29
8     34
9     23
10    23
11    45
12    21
13    37
14    30
dtype: int64

In [20]:
s=pd.Series(a)

0     34
1     41
2     29
3     47
4     39
5     31
6     25
7     29
8     34
9     23
10    23
11    45
12    21
13    37
14    30
dtype: int64

In [36]:
np.random.seed(590)
b=np.random.randint(100,200,(6,5))

In [37]:
b.ndim

2

In [38]:
b

array([[155, 196, 143, 137, 105],
       [165, 135, 186, 111, 148],
       [128, 119, 162, 174, 166],
       [172, 177, 152, 120, 103],
       [196, 164, 182, 124, 161],
       [184, 148, 106, 135, 122]])

In [40]:
pd.DataFrame(b)

     0    1    2    3    4
0  155  196  143  137  105
1  165  135  186  111  148
2  128  119  162  174  166
3  172  177  152  120  103
4  196  164  182  124  161
5  184  148  106  135  122

In [49]:
df=pd.DataFrame(b,columns=['Roll no','Name','Age','Section','Country'],index=[182,183,184,185,186,187])
df

     Roll no  Name  Age  Section  Country
182      155   196  143      137      105
183      165   135  186      111      148
184      128   119  162      174      166
185      172   177  152      120      103
186      196   164  182      124      161
187      184   148  106      135      122

In [51]:
df.loc[182]

Roll no    155
Name       196
Age        143
Section    137
Country    105
Name: 182, dtype: int64

In [54]:
df.iloc[0,0]

155

In [58]:
df.loc[182,['Roll no','Name','Age']]

Roll no    155
Name       196
Age        143
Name: 182, dtype: int64

In [59]:
df.iloc[0,0:3]

Roll no    155
Name       196
Age        143
Name: 182, dtype: int64

In [60]:
df.iloc[0,[0,1,2]]

Roll no    155
Name       196
Age        143
Name: 182, dtype: int64

In [61]:
df.iloc[[0,5]]

     Roll no  Name  Age  Section  Country
182      155   196  143      137      105
187      184   148  106      135      122

In [62]:
df.iloc[[1,3,4]]

     Roll no  Name  Age  Section  Country
183      165   135  186      111      148
185      172   177  152      120      103
186      196   164  182      124      161

In [64]:
df.loc[[182,183,184]]

     Roll no  Name  Age  Section  Country
182      155   196  143      137      105
183      165   135  186      111      148
184      128   119  162      174      166

In [65]:
df.loc[[182,185,186],['Section','Name','Age']]

     Section  Name  Age
182      137   196  143
185      120   177  152
186      124   164  182

In [68]:
type(df)

pandas.core.frame.DataFrame